# Generated by Django 5.1 on 2024-08-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taskName', models.CharField(max_length=100)),
                ('dueDate', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Not Been Started'), (2, 'In Progress'), (3, 'Pending')])),
                ('team', models.IntegerField(choices=[(1, 'WorkFlow Team'), (2, 'Software Team'), (3, 'Accounting Team'), (4, 'Quality Assurance Team'), (5, 'Testing Team')])),
            ],
        ),
    ]
