# Generated by Django 5.1 on 2024-08-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taskName', models.CharField(max_length=100)),
                ('report', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Not Been Started', 'Not Been Started'), ('In Progress', 'In Progress'), ('Pending', 'Pending')], max_length=40),
        ),
        migrations.AlterField(
            model_name='task',
            name='team',
            field=models.CharField(choices=[('WorkFlow Team', 'WorkFlow Team'), ('Software Team', 'Software Team'), ('Accounting Team', 'Accounting Team'), ('Quality Assurance Team', 'Quality Assurance Team'), ('Testing Team', 'Testing Team')], max_length=50),
        ),
    ]
